name: pre-commit

on:
  pull_request:
  push:
    branches: [master]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      -  uses: actions/setup-python@v1
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Cache virtualenv
        uses: actions/cache@v1
        id: cache-pip
        with:
          path: venv
          key: venv-${{ hashFiles('setup.py') }}-${{ matrix.python-version }}-${{ matrix.os }}
      - name: Install dependencies in a venv
        if: steps.cache-pip.outputs.cache-hit != 'true'
        run: |
          python3 -m venv venv
          . venv/bin/activate
          pip install -q -U pip
          pip install --progress-bar=off .[all,reports,testing]

      - name: Lint
        run: make lint
